### PR TITLE
Tove could not load native libraries

### PR DESCRIPTION
**Pull request by Ezbob**
**What is the problem?**
I have tried to run the game but could not load Tove native dynamic libraries. 
 
**What is the solution?**
I have reworked the path resolving algorithm in the included Tove library, such that it:
  1. Can be controlled by a Environmental variable "TOVE_DYNAMIC_LIB_PREFIX"
  2. Can be automatically resolved with a extension to the current debug reflection solution that uses absolute paths instead of relative paths

### CODE REVIEW

**Comment by Ezbob** [comment]
BTW. I am working from a Windows 10 machine.

**Comment by Tiggles** [comment]
This is the issue if you run the game by `love <folder_name>` and not `love .` inside the game folder, right?

**Comment by Ezbob** [comment]
That is one of the symptoms of it, yeah.

**Comment by xiroV** [comment]
If I understand correctly, this is an issue with the dependency (Tove), and not awesome-chess, am I right?

If that is the case, this should probably be solved in Tove, and not here, as if we decide to upgrade to a newer version of Tove, we would have to fix this again.

On a related note, I'm not even sure if this is the correct way to handle dependencies in the first place, or if it can be automated in some way, such that the dependencies are not bundled with the source.

**Comment by Ezbob** [comment]
I have create a pull request in tove2d.

**Pull request closed without merging**
